### ISSUE TITLE
Size mismatch, m1: [5*278528], m2: [512*512] at 

### ISSUE THREAD

**Issue by xunyuc2** [joonson/syncnet_python#22]
Dear author, 

Thank you for this excellent work! 

I ran into a problem when running on a video. At first, my CUDA memory ran out so I reduced the batch size to 5. And then I got into this error: 

Runtime Error: Size mismatch, m1: [5*278528], m2: [512*512] at 
Traceback (most recent call last):
  File "demo_syncnet.py", line 30, in <module>
    s.evaluate(opt, videofile=opt.videofile)
  File "C:\XC\syncnet_python\SyncNetInstance.py", line 112, in evaluate
    im_out  = self.__S__.forward_lip(im_in.cuda());
  File "C:\XC\syncnet_python\SyncNetModel.py", line 108, in forward_lip
    out = self.netfclip(mid);
  File "C:\Users\xunyu\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\xunyu\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\xunyu\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\xunyu\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\xunyu\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [5 x 278528], m2: [512 x 512] at C:/w/1/s/tmp_conda_3.7_100118/conda/conda-bld/pytorch_1579082551706/work/aten/src\THC/generic/THCTensorMathBlas.cu:290

Could you take a look at this issue at your convenience? Thanks a lot!

**Comment by EhsanRusta** [comment]
did you solved this issue?

**Comment by EhsanRusta** [comment]
@xunyuc2
