### ISSUE TITLE
Demo Not Working (RuntimeError: mat1 dim 1 must match mat2 dim 0)

### ISSUE THREAD

**Issue by avisekiit** [joonson/syncnet_python#30]
Dear Authors,
Firstly, thanks for releasing the codes and the models.

I could run your demo code with the data/example.avi as suggested in the readme.
However, when I try to run that same demo with one of my .avi files, I get the below runtime error.
[Here](https://drive.google.com/file/d/1kl1BS9oqATLHJelVZwN_jXRi1D3_L-L9/view?usp=sharing) is my video file
Any guidance to mitigate this will be really appreciated.

`Traceback (most recent call last):
  File "demo_syncnet.py", line 30, in <module>
    s.evaluate(opt, videofile=opt.videofile)
  File "/data/syncnet_python/SyncNetInstance.py", line 112, in evaluate
    im_out  = self.__S__.forward_lip(im_in.cuda());
  File "/data/syncnet_python/SyncNetModel.py", line 108, in forward_lip
    out = self.netfclip(mid);
  File "/usr/local/google/home/avisek/anaconda2/envs/syncnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/google/home/avisek/anaconda2/envs/syncnet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/google/home/avisek/anaconda2/envs/syncnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/google/home/avisek/anaconda2/envs/syncnet/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/google/home/avisek/anaconda2/envs/syncnet/lib/python3.6/site-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
`

**Comment by dipam7** [comment]
Were you able to solve this? I am getting the same error

**Comment by joonson** [comment]
If your video file is not 224x224 at 25 fps, you will need to run `run_pipeline.py` first.

**Comment by QUTGXX** [comment]
> If your video file is not 224x224 at 25 fps, you will need to run `run_pipeline.py` first.

Hi, I got the same error. And I have run the 'run_pipeline.py' and it produces many results including pyavi, pycrop, pyframes, pytemp and pywork. Could you please tell me what is it? And after this step, What I should do?

**Comment by avisekiit** [comment]
Thanks. Closing this now.

**Comment by Unmesh28** [comment]
@avisekiit I am facing similar issue. How did you resolve it ?

**Comment by ThetaRgo** [comment]
> And I have run the 'run_pipeline.py' and it produces many results including pyavi, pycrop, pyframes, pytemp and pywork. Could you please tell me what is it? And after this step, What I should do?

hello,bug not solved,i have run_pipeline.py first and use the result avi files in pyavis folder to run demo,but get the same error
