### ISSUE TITLE
File not found issue when I tried to run the demo

### ISSUE THREAD

**Issue by houdajun** [joonson/syncnet_python#36]
~/syncnet_python$ python demo_syncnet.py --videofile data/1.mp4 --tmp_dir temp_dir
Traceback (most recent call last):
  File "demo_syncnet.py", line 27, in <module>
    s.loadParameters(opt.initial_model);
  File "/home/dajun/syncnet_python/SyncNetInstance.py", line 202, in loadParameters
    loaded_state = torch.load(path, map_location=lambda storage, loc: storage);
  File "/home/dajun/anaconda3/envs/syncnet/lib/python3.6/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dajun/anaconda3/envs/syncnet/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dajun/anaconda3/envs/syncnet/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/syncnet_v2.model'

Please help.

**Comment by houdajun** [comment]
figured that out, need to run the shell script: sh download_model.sh
