### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Unmesh28** [joonson/syncnet_python#54]
> after running "run_pipeline.py", I am getting this error :  

`Stream mapping:
  Stream #0:1 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to './synced_output/pyavi/0000.mp4/audio.wav':
  Metadata:
    ISFT            : Lavf57.83.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc57.107.100 pcm_s16le
size=     137kB time=00:00:04.39 bitrate= 256.1kbits/s speed= 391x    
video:0kB audio:137kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.055499%
[S3FD] loading with cuda
Traceback (most recent call last):
  File "./run_pipeline.py", line 294, in <module>
    faces = inference_video(opt)
  File "./run_pipeline.py", line 187, in inference_video
    DET = S3FD(device='cuda')
  File "/media/SSD/syncnet_python/detectors/s3fd/__init__.py", line 22, in __init__
    state_dict = torch.load(PATH_WEIGHT, map_location=self.device)
  File "/home/administrator/anaconda3/envs/sync1/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/administrator/anaconda3/envs/sync1/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
`

**Comment by yhcsyz** [comment]
这个是模型没有加载完全 v2.model没成功

**Comment by makeiot** [comment]
> 这个是模型没有加载完全 v2.model没成功

知道怎么解决吗？
